#!/usr/bin/env bash

White=$'\e[0m'
Yellow=$'\e[1;33m'

cd flutter clean && flutter pub get && cd packages
for d in ./*/ ; 
    do (
        echo $Yellow 
        echo ⌈‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾⌉
        echo    √       start at $d 
        echo ⌊______________________________________⌋
        echo $White
        cd "$d" && flutter pub get 
        # && flutter pub run build_runner build --delete-conflicting-outputs        
    );
done

printf "\e[33;1m%s\e[0m\n" 'Touch on *.freezed.dart models'
find . -name "*.freezed.dart" -type f -exec touch {} \;

printf "\e[33;1m%s\e[0m\n" 'Touch on *.g.dart models'
find . -name "*.g.dart" -type f -exec touch {} \;